### PR TITLE
Front End Project Setup and a LoginComponent

### PR DESCRIPTION
**Pull request by rdev0rigin**
This PR will introduce a few new things for the front end. I refactored the `src/frontend` directory with a **ReactJS**, **SASS**, and **TypeScript**  development flow. The frontend directory contains a `src/` and should not be confused with the document roots src folder. For the rest of the following text we are considering only files and folders within the `src/frontend/` directory. 

I also provided a login form component within `src/components/login/login.component.tsx`

# Development Flow and IA
> TypeScript files can transpile with regular ES* JavaScript as well.

The IA is built around a few simple paradigms that focus on modularity and sass theme packs. For right now Bootstrap is being used and so I am building with an OOSCSS Pattern with the hope to allow Bootstrap to be more easily swapped, if the want arises. 

## React Scripts / NPM
This project is using react scripts and it provides the following script commands in the `package.json`
```json
{
 "scripts": {
    "start": "react-scripts-ts start",
    "build": "react-scripts-ts build",
    "test": "react-scripts-ts test --env=jsdom",
    "eject": "react-scripts-ts eject"
  }
}
```

Use `npm run start` to launch the DevServer and `npm run build` to make a production bundle. 

## The Main App

`Index.tsx` initializes the project and `App.tsx`  is the main hub and landing view. From here we can build the main view and provide the beginning of the UX flow.  

## React Components

The front end is using ReactJS as a  UI library and each ReactJS component is contained in their own folder along with their accompanying tests and style sheets.

## Styles

There is a global style folder `/styles` as well as a main style sheet for loading and providing global scoped variables and styles in `main.style.scss`

# LoginComponent

The `LoginComponent` is just aesthetic, it contains no functionality yet.

screen shot 2018-11-30 at 6 30 06 pm

### CODE REVIEW

**Comment by rdev0rigin** [comment]
Created a PR https://github.com/CodeForPortland/recordexpungPDX/pull/30

**Comment by rdev0rigin** [comment]
@NickSchimek, I also built off of @hmarcks branch. I would appreciate a style and code sniff from both of you.

**Comment by hmarcks** [comment]
@rdev0rigin Awesome, thanks for getting this started!

I'm just going to comment on the css/html perspective (I'm not qualified in js). I'd like to try and use [Tachyons](http://tachyons.io/) for most of our styles, and use BEM syntax for more specialized styling scenarios where Tachyons doesn't cover (globals.style.scss). My goal is to eventually create some components (stack on Tachyons classes) that will act as a style guide, but the search.html page has some examples of the styles I'd like to follow.

I don't have my dev environment set up yet, but here's an example of how the login view can be styled with no custom css: https://codepen.io/hmarcks/project/editor/AgzzJx

Let me know what you think, thanks much

**Comment by rdev0rigin** [comment]
@hmarcks Tachyon's is being implement now via a CDN from a `<link/>` in the `public/index.html`. The theme's looking good 👍. I made a selfish change for the forgot password link to hover to hot pink... we can change it later :P 

## Two Things to Note About Styles
I am trying to separate the style and logic a bit but there are two main ways of implementing styles on a component's template.

- `main.style.scss` - Styles in here will provide a trickle down affect for anything inside the main `App.tsx` component

- `import './component.style.scss` - Style sheets can also be imported into a component and will be encapsulated and should also take precedence in the cascading order however it could be overridden based on selection specificity and `!important`. In short, in theory this should work. :

### Also..
I tried to and will continue to use *BEM* naming conventions. Let me know, if I can do better here!  

Thanks!

**Comment by NickSchimek** [comment]
Thanks for reviewing this @drewlearnsabout

**Comment by rbeatie** [comment]
(This is Rex, Im on my other computer.) @drewlearnsabout TY for the review!

**Comment by rdev0rigin** [comment]
Merged PR and removing branch

**Pull request merged**
